import React from 'react';
import {
  Document, Page, Text, View, Image, StyleSheet, renderToBuffer, Font,
} from '@react-pdf/renderer';
import fs from 'fs';
import path from 'path';
import type { IDocument, IDocSection } from '../models/Document';
import type { IRequirement } from '../models/Requirement';

Font.register({
  family: 'Helvetica',
  fonts: [{ src: 'Helvetica' }, { src: 'Helvetica-Bold', fontWeight: 'bold' }],
});

const styles = StyleSheet.create({
  page: { fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a2e', paddingTop: 60, paddingBottom: 60, paddingHorizontal: 50 },
  // Cover
  coverPage: { fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a2e', padding: 0, display: 'flex', flexDirection: 'column' },
  coverHeader: { backgroundColor: '#0f3460', padding: 40, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  coverLogo: { width: 80, height: 40, objectFit: 'contain' },
  coverLogoText: { fontSize: 22, fontWeight: 'bold', color: '#fff' },
  coverBody: { padding: 50, flex: 1 },
  coverTitle: { fontSize: 28, fontWeight: 'bold', color: '#0f3460', marginBottom: 12 },
  coverSubtitle: { fontSize: 14, color: '#555', marginBottom: 40 },
  coverMeta: { marginTop: 8 },
  coverMetaRow: { flexDirection: 'row', marginBottom: 6 },
  coverMetaLabel: { width: 100, fontSize: 10, color: '#888' },
  coverMetaValue: { fontSize: 10, color: '#1a1a2e', fontWeight: 'bold' },
  coverFooter: { backgroundColor: '#f0f4ff', padding: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  coverFooterText: { fontSize: 9, color: '#666' },
  // Watermark
  watermark: { position: 'absolute', top: '40%', left: '10%', fontSize: 72, color: '#e5e7eb', opacity: 0.3, transform: 'rotate(-35deg)' },
  // Header/Footer
  header: { position: 'absolute', top: 20, left: 50, right: 50, flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#e5e7eb', paddingBottom: 6 },
  headerText: { fontSize: 8, color: '#999' },
  footer: { position: 'absolute', bottom: 20, left: 50, right: 50, flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#e5e7eb', paddingTop: 6 },
  footerText: { fontSize: 8, color: '#999' },
  pageNumber: { fontSize: 8, color: '#999' },
  // Content
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#0f3460', marginBottom: 8, marginTop: 20, paddingBottom: 4, borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  sectionContent: { fontSize: 10, color: '#333', lineHeight: 1.6, marginBottom: 12 },
  reqBlock: { backgroundColor: '#f8faff', borderLeftWidth: 3, borderLeftColor: '#0f3460', padding: 8, marginBottom: 6 },
  reqId: { fontSize: 8, color: '#0f3460', fontWeight: 'bold', marginBottom: 2 },
  reqTitle: { fontSize: 9, color: '#1a1a2e', marginBottom: 2 },
  reqMeta: { fontSize: 8, color: '#888' },
  toc: { marginTop: 20 },
  tocRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6, paddingBottom: 4, borderBottomWidth: 1, borderBottomColor: '#f0f0f0' },
  tocTitle: { fontSize: 10, color: '#1a1a2e' },
  tocPage: { fontSize: 10, color: '#888' },
});

interface PdfProps {
  doc:       IDocument;
  project:   { name: string; clientName: string };
  reqMap:    Map<string, IRequirement>;
  logoPath?: string;
  companyName: string;
}

function PageHeader({ title, companyName }: { title: string; companyName: string }) {
  return (
    <View style={styles.header} fixed>
      <Text style={styles.headerText}>{companyName} — Confidential</Text>
      <Text style={styles.headerText}>{title}</Text>
    </View>
  );
}

function PageFooter({ status }: { status: string }) {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>Generated by NEXUS — {new Date().toLocaleDateString()}</Text>
      <Text style={styles.pageNumber} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} fixed />
      <Text style={styles.footerText}>{status.toUpperCase()}</Text>
    </View>
  );
}

function SrsDocument({ doc, project, reqMap, logoPath, companyName }: PdfProps) {
  const isApproved = doc.status === 'approved';
  const watermarkText = isApproved ? 'APPROVED' : 'DRAFT';

  const logoData = logoPath && fs.existsSync(logoPath)
    ? `data:image/png;base64,${fs.readFileSync(logoPath).toString('base64')}`
    : null;

  return (
    <Document title={doc.title} author={companyName}>
      {/* Cover page */}
      <Page size="A4" style={styles.coverPage}>
        <View style={styles.coverHeader}>
          {logoData
            ? <Image src={logoData} style={styles.coverLogo} />
            : <Text style={styles.coverLogoText}>{companyName}</Text>
          }
          <Text style={{ fontSize: 10, color: 'rgba(255,255,255,0.7)' }}>NEXUS SDLC Platform</Text>
        </View>

        <View style={styles.coverBody}>
          <Text style={styles.coverTitle}>{doc.title}</Text>
          <Text style={styles.coverSubtitle}>{doc.type.toUpperCase().replace('_', ' ')}</Text>

          <View style={styles.coverMeta}>
            {[
              ['Project',   project.name],
              ['Client',    project.clientName],
              ['Version',   doc.version],
              ['Status',    doc.status.replace('_', ' ').toUpperCase()],
              ['Date',      new Date().toLocaleDateString()],
            ].map(([label, value]) => (
              <View key={label} style={styles.coverMetaRow}>
                <Text style={styles.coverMetaLabel}>{label}</Text>
                <Text style={styles.coverMetaValue}>{value}</Text>
              </View>
            ))}
          </View>
        </View>

        <View style={styles.coverFooter}>
          <Text style={styles.coverFooterText}>Confidential — {companyName}</Text>
          <Text style={styles.coverFooterText}>{isApproved ? '✓ Approved Document' : 'Draft — Subject to Change'}</Text>
        </View>
      </Page>

      {/* Table of Contents */}
      <Page size="A4" style={styles.page}>
        <PageHeader title={doc.title} companyName={companyName} />
        <Text style={styles.watermark}>{watermarkText}</Text>
        <Text style={styles.sectionTitle}>Table of Contents</Text>
        <View style={styles.toc}>
          {doc.sections.map((s, i) => (
            <View key={s.id} style={styles.tocRow}>
              <Text style={styles.tocTitle}>{i + 1}. {s.title}</Text>
              <Text style={styles.tocPage}>—</Text>
            </View>
          ))}
        </View>
        <PageFooter status={doc.status} />
      </Page>

      {/* Content pages */}
      {doc.sections.map((section: IDocSection, i: number) => (
        <Page key={section.id} size="A4" style={styles.page}>
          <PageHeader title={doc.title} companyName={companyName} />
          <Text style={styles.watermark}>{watermarkText}</Text>

          <Text style={styles.sectionTitle}>{i + 1}. {section.title}</Text>

          {section.content && (
            <Text style={styles.sectionContent}>{section.content}</Text>
          )}

          {section.linkedReqs?.length > 0 && (
            <View>
              <Text style={{ fontSize: 10, fontWeight: 'bold', color: '#555', marginBottom: 6 }}>
                Linked Requirements
              </Text>
              {section.linkedReqs.map((rid) => {
                const req = reqMap.get(rid.toString());
                if (!req) return null;
                return (
                  <View key={rid.toString()} style={styles.reqBlock}>
                    <Text style={styles.reqId}>{req.reqId}</Text>
                    <Text style={styles.reqTitle}>{req.title}</Text>
                    <Text style={styles.reqMeta}>{req.type} · {req.priority} · {req.status}</Text>
                    {req.acceptanceCriteria && (
                      <Text style={{ ...styles.reqMeta, marginTop: 4 }}>AC: {req.acceptanceCriteria}</Text>
                    )}
                  </View>
                );
              })}
            </View>
          )}

          <PageFooter status={doc.status} />
        </Page>
      ))}
    </Document>
  );
}

export async function generateSrsPdf(
  doc: IDocument,
  project: { name: string; clientName: string },
  reqMap: Map<string, IRequirement>,
  settings: { logoPath?: string; companyName: string },
): Promise<Buffer> {
  const element = React.createElement(SrsDocument, {
    doc, project, reqMap,
    logoPath: settings.logoPath,
    companyName: settings.companyName,
  });
  return await renderToBuffer(element);
}

export const IEEE_830_SECTIONS = [
  { id: 'introduction',    title: 'Introduction',                    order: 0 },
  { id: 'scope',           title: 'Scope',                           order: 1 },
  { id: 'definitions',     title: 'Definitions & Acronyms',          order: 2 },
  { id: 'overall',         title: 'Overall Description',             order: 3 },
  { id: 'functional',      title: 'Functional Requirements',         order: 4 },
  { id: 'non_functional',  title: 'Non-Functional Requirements',     order: 5 },
  { id: 'constraints',     title: 'Constraints',                     order: 6 },
  { id: 'appendices',      title: 'Appendices',                      order: 7 },
];
